apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-k8s-deployment
  labels:
    app: devops-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-k8s
  template:
    metadata:
      labels:
        app: devops-k8s
    spec:
      containers:
      - name: devops-k8s
        image: ababic89/devops-k8s:v0.1
        ports:
        - containerPort: 80
          name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: devops-k8s-service
spec:
  selector:
    app: devops-k8s
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http-web-svc
